// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2VulotKKBzn7vjC9jtcP-oUEenBB-CM',
    appId: '1:1078148836976:web:4fc614c47624c85c7fceb5',
    messagingSenderId: '1078148836976',
    projectId: 'fireflutter-1-23057',
    authDomain: 'fireflutter-1-23057.firebaseapp.com',
    storageBucket: 'fireflutter-1-23057.appspot.com',
    measurementId: 'G-KD7SF88V78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKAdoGfIFYR92su2uVu9724wCrZDgCHaw',
    appId: '1:1078148836976:android:38be7063de5ee1727fceb5',
    messagingSenderId: '1078148836976',
    projectId: 'fireflutter-1-23057',
    storageBucket: 'fireflutter-1-23057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1NrQfNPMeKLi-07u6fPG4Nvk7SOY3Sk',
    appId: '1:1078148836976:ios:fe5b90cf89fbe40e7fceb5',
    messagingSenderId: '1078148836976',
    projectId: 'fireflutter-1-23057',
    storageBucket: 'fireflutter-1-23057.appspot.com',
    iosBundleId: 'com.example.finalExam1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR1NrQfNPMeKLi-07u6fPG4Nvk7SOY3Sk',
    appId: '1:1078148836976:ios:fe5b90cf89fbe40e7fceb5',
    messagingSenderId: '1078148836976',
    projectId: 'fireflutter-1-23057',
    storageBucket: 'fireflutter-1-23057.appspot.com',
    iosBundleId: 'com.example.finalExam1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX2VulotKKBzn7vjC9jtcP-oUEenBB-CM',
    appId: '1:1078148836976:web:cfda87c4c6bf9f767fceb5',
    messagingSenderId: '1078148836976',
    projectId: 'fireflutter-1-23057',
    authDomain: 'fireflutter-1-23057.firebaseapp.com',
    storageBucket: 'fireflutter-1-23057.appspot.com',
    measurementId: 'G-2MZFQHWEQZ',
  );
}
